Repository apollographql/react-apollo, pull requests merged in 2018-12, with the labels that each got.

#2573 Expose graphql hocs to allow choosing them explicitly and improve typing
  src/browser.ts
  src/graphql.tsx
  src/mutation-hoc.tsx
  src/query-hoc.tsx
  src/subscription-hoc.tsx
Labels: feature

#2695 Remove skipLibCheck, add lib "esnext.asynciterable"
  package-lock.json
  tsconfig.json
Labels: typescript

#2483 Update README.md
  README.md
Labels: docs
