Repository apollographql/react-apollo, pull requests merged in 2018-08, with the labels that each got.

#2236 Updated changelog with some forgotten changes
  Changelog.md
Labels: docs

#1998 Example of a mutation including tests
  examples/mutation/.gitignore
  examples/mutation/package.json
  examples/mutation/public/favicon.ico
  examples/mutation/public/index.html
  examples/mutation/public/manifest.json
  examples/mutation/src/__snapshots__/addUser.test.js.snap
  examples/mutation/src/addUser.js
  examples/mutation/src/addUser.test.js
  examples/mutation/src/index.css
  examples/mutation/src/index.js
Labels: in-progress

#1966 Feature: add onSubscriptionData callback to <Subscription>
  Changelog.md
  src/Subscriptions.tsx
  test/client/Subscription.test.tsx
Labels: in-progress

#1968 Don't mutate options object when calculating variables from props
  Changelog.md
  src/query-hoc.tsx
  test/client/graphql/queries/index.test.tsx
Labels: in-progress

#1983 Query: Fix data is undefined on error
  Changelog.md
  src/Query.tsx
  src/Subscriptions.tsx
  test/client/Query.test.tsx
  test/client/Subscription.test.tsx
  test/client/getDataFromTree.test.tsx
Labels: in-progress

#2254 test-utils: allow passing a custom cache object to `MockedProvider`
  Changelog.md
  src/test-utils.tsx
  test/test-utils.test.tsx
Labels: feature, in-progress

#2284 Make mock links mock parameter readonly
  Changelog.md
  src/test-links.ts
  src/test-utils.tsx
  test/test-utils.test.tsx
Labels: in-progress

#2281 Replace duplicate ObservableQueryFields types defined in apollo-client
  Changelog.md
  src/Query.tsx
Labels: in-progress, typescript

#2208 type graphql.options.skip HOC property
  Changelog.md
  src/types.ts
  test/client/getDataFromTree.test.tsx
Labels: in-progress

#2045 Avoid importing lodash directly
  Changelog.md
  dangerfile.ts
  examples/base/src/__tests__/App.js
  examples/typescript/src/App.tsx
  examples/typescript/src/Character.tsx
  examples/typescript/src/__tests__/Character.tsx
  examples/typescript/src/index.tsx
  src/ApolloConsumer.tsx
  src/ApolloProvider.tsx
  src/Mutation.tsx
  src/Query.tsx
  src/Subscriptions.tsx
  src/getDataFromTree.ts
  src/graphql.tsx
  src/hoc-utils.tsx
  src/mutation-hoc.tsx
  src/query-hoc.tsx
  src/renderToStringWithData.ts
  src/subscription-hoc.tsx
  src/test-utils.tsx
  src/withApollo.tsx
  test/client/ApolloConsumer.test.tsx
  test/client/ApolloProvider.test.tsx
  test/client/Mutation.test.tsx
  test/client/Query.test.tsx
  test/client/Subscription.test.tsx
  test/client/getDataFromTree.test.tsx
  test/client/graphql/client-option.test.tsx
  test/client/graphql/fragments.test.tsx
  test/client/graphql/mutations/index.test.tsx
  test/client/graphql/mutations/lifecycle.test.tsx
  test/client/graphql/mutations/queries.test.tsx
  test/client/graphql/mutations/recycled-queries.test.tsx
  test/client/graphql/queries/api.test.tsx
  test/client/graphql/queries/errors.test.tsx
  test/client/graphql/queries/index.test.tsx
  test/client/graphql/queries/lifecycle.test.tsx
  test/client/graphql/queries/loading.test.tsx
  test/client/graphql/queries/observableQuery.test.tsx
  test/client/graphql/queries/polling.test.tsx
  test/client/graphql/queries/reducer.test.tsx
  test/client/graphql/queries/skip.test.tsx
  test/client/graphql/queries/updateQuery.test.tsx
  test/client/graphql/shared-operations.test.tsx
  test/client/graphql/statics.test.tsx
  test/client/graphql/subscriptions.test.tsx
  test/flow-usage.js
  test/server/server.test.tsx
  test/test-utils.test.tsx
  test/test-utils/enzyme.ts
  test/typescript-usage.tsx
  tsconfig.json
Labels: in-progress
