Repository apollographql/react-apollo, pull requests merged in 2018-10, with the labels that each got.

#2449 Moved lodash.isequal to dependencies
  package-lock.json
  package.json
Labels: blocking

#2311 TVariables generic should be passed to ObservableQuery
  src/Query.tsx
Labels: typescript

#2513 Remove all destructive precommit hooks.
  package-lock.json
  package.json
Labels: in-progress
