Repository apollographql/react-apollo, pull requests merged in 2019-03, with the labels that each got.

#2839 Add a basic example app bundled with Rollup.
  examples/rollup/.gitignore
  examples/rollup/index.html
  examples/rollup/main.js
  examples/rollup/package-lock.json
  examples/rollup/package.json
  examples/rollup/rollup.config.js
Labels: bundle-size, tooling

#2842 Bundle reductions inspired by examples/rollup app.
  package.json
  rollup.config.js
  src/Query.tsx
Labels: bundle-size

#2482 [Feature Request] MockedProvider can pass down props to child component
  Changelog.md
  src/test-utils.tsx
  test/test-utils.test.tsx
Labels: feature

#2496 Support destructuring onCompleted callback params
  Changelog.md
  src/Query.tsx
Labels: typescript

#2525 Added graphql hoc missing data type generic
  Changelog.md
  src/Query.tsx
  src/types.ts
  test/typescript-usage.tsx
Labels: typescript

#2540 Refactor ApolloProvider/ApolloConsumer implementation to use React 16.3 context API
  Changelog.md
  package-lock.json
  package.json
  src/ApolloConsumer.tsx
  src/ApolloContext.ts
  src/ApolloProvider.tsx
Labels: feature
